/**
 * Auto-generated by `supabase gen types typescript` (via Supabase MCP).
 * Regenerate after every schema migration: do not hand-edit.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      sales_activity: {
        Row: {
          action: string;
          actor_id: string;
          created_at: string;
          id: string;
          metadata: Json | null;
          target_id: string | null;
          target_type: string | null;
        };
        Insert: {
          action: string;
          actor_id: string;
          created_at?: string;
          id?: string;
          metadata?: Json | null;
          target_id?: string | null;
          target_type?: string | null;
        };
        Update: {
          action?: string;
          actor_id?: string;
          created_at?: string;
          id?: string;
          metadata?: Json | null;
          target_id?: string | null;
          target_type?: string | null;
        };
        Relationships: [];
      };
      sales_assessments: {
        Row: {
          brief_input_ready: boolean | null;
          coverage_score: number | null;
          created_at: string;
          created_by: string;
          firm_city: string;
          firm_name: string;
          firm_practice_area: string;
          firm_state: string;
          firm_url: string;
          id: string;
          recommendation: Json | null;
          report: Json;
          updated_at: string;
        };
        Insert: {
          brief_input_ready?: boolean | null;
          coverage_score?: number | null;
          created_at?: string;
          created_by: string;
          firm_city: string;
          firm_name: string;
          firm_practice_area: string;
          firm_state: string;
          firm_url: string;
          id?: string;
          recommendation?: Json | null;
          report: Json;
          updated_at?: string;
        };
        Update: {
          brief_input_ready?: boolean | null;
          coverage_score?: number | null;
          created_at?: string;
          created_by?: string;
          firm_city?: string;
          firm_name?: string;
          firm_practice_area?: string;
          firm_state?: string;
          firm_url?: string;
          id?: string;
          recommendation?: Json | null;
          report?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      sales_briefs: {
        Row: {
          assessment_id: string;
          body_md: string;
          cache_read_tokens: number | null;
          cache_write_tokens: number | null;
          created_at: string;
          generated_by: string;
          id: string;
          input_tokens: number | null;
          output_tokens: number | null;
        };
        Insert: {
          assessment_id: string;
          body_md: string;
          cache_read_tokens?: number | null;
          cache_write_tokens?: number | null;
          created_at?: string;
          generated_by: string;
          id?: string;
          input_tokens?: number | null;
          output_tokens?: number | null;
        };
        Update: {
          assessment_id?: string;
          body_md?: string;
          cache_read_tokens?: number | null;
          cache_write_tokens?: number | null;
          created_at?: string;
          generated_by?: string;
          id?: string;
          input_tokens?: number | null;
          output_tokens?: number | null;
        };
        Relationships: [];
      };
      sales_calls: {
        Row: {
          assessment_id: string;
          closer_id: string | null;
          contract_value_cents: number | null;
          created_at: string;
          duration_seconds: number | null;
          ended_at: string | null;
          id: string;
          notes: string | null;
          objections_hit: string[] | null;
          opener_id: string;
          outcome: Database["public"]["Enums"]["sales_call_outcome"] | null;
          package_sold: string | null;
          started_at: string;
          transcript_excerpt: string | null;
          triggers_hit: string[] | null;
        };
        Insert: {
          assessment_id: string;
          closer_id?: string | null;
          contract_value_cents?: number | null;
          created_at?: string;
          duration_seconds?: number | null;
          ended_at?: string | null;
          id?: string;
          notes?: string | null;
          objections_hit?: string[] | null;
          opener_id: string;
          outcome?: Database["public"]["Enums"]["sales_call_outcome"] | null;
          package_sold?: string | null;
          started_at?: string;
          transcript_excerpt?: string | null;
          triggers_hit?: string[] | null;
        };
        Update: {
          assessment_id?: string;
          closer_id?: string | null;
          contract_value_cents?: number | null;
          created_at?: string;
          duration_seconds?: number | null;
          ended_at?: string | null;
          id?: string;
          notes?: string | null;
          objections_hit?: string[] | null;
          opener_id?: string;
          outcome?: Database["public"]["Enums"]["sales_call_outcome"] | null;
          package_sold?: string | null;
          started_at?: string;
          transcript_excerpt?: string | null;
          triggers_hit?: string[] | null;
        };
        Relationships: [];
      };
      sales_profiles: {
        Row: {
          active: boolean;
          created_at: string;
          email: string;
          full_name: string | null;
          id: string;
          last_seen_at: string | null;
          role: Database["public"]["Enums"]["sales_role"];
        };
        Insert: {
          active?: boolean;
          created_at?: string;
          email: string;
          full_name?: string | null;
          id: string;
          last_seen_at?: string | null;
          role?: Database["public"]["Enums"]["sales_role"];
        };
        Update: {
          active?: boolean;
          created_at?: string;
          email?: string;
          full_name?: string | null;
          id?: string;
          last_seen_at?: string | null;
          role?: Database["public"]["Enums"]["sales_role"];
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: {
      sales_call_outcome:
        | "closed_won"
        | "closed_lost"
        | "follow_up_scheduled"
        | "no_decision"
        | "not_interested"
        | "callback_requested";
      sales_role: "opener" | "closer" | "admin";
    };
    CompositeTypes: { [_ in never]: never };
  };
};
